feat: add .clang-format
Signed-off-by: saurabhraghuvanshii <saurabhsraghuvanshi@gmail.com>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -13,6 +13,33 @@ permissions:
   contents: read
 
 jobs:
+  format:
+    name: Format check
+    runs-on: macos-15
+    timeout-minutes: 10
+    steps:
+      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
+        with:
+          fetch-depth: 1
+      - name: Install clang-format
+        run: brew install clang-format
+      - name: Check code
+        run: |
+          # Format all source - fi the source is formatted properly this will do nothing
+          clang-format -i *.c *.h client/*.c
+
+          # Do we have unwanted changes?
+          if ! git diff-index --quiet HEAD; then
+              # Show the changes
+              echo "ERROR: Code is not properly formatted:"
+              echo
+              git --no-pager diff
+
+              echo
+              echo >&2 "Please run clang-format locally and commit the changes."
+              exit 1
+          fi
+
   build:
     name: Build
     strategy:
@@ -36,4 +63,3 @@ jobs:
           fix: true # Enabled to improve reported errors
           globs: '**/*.md'
           config: '.markdownlint.json'
-          
